version: "3.9"

services:
  db:
    image: postgres:16
    container_name: smartmart_db
    environment:
      POSTGRES_DB: smartmart
      POSTGRES_USER: root_smartmart
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: smartmart_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      NAME_DB: smartmart
      USER_DB: root_smartmart
      PASSWORD_DB: rootpassword
      HOST_DB: smartmart_db
      PORT_DB: 5432

volumes:
  postgres_data:
