version: "3.9"

services:
  db:
    image: postgres:16
    container_name: smartmart_db
    environment:
      POSTGRES_DB: smartmart
      POSTGRES_USER: root_smartmart
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
